name: food_recognizer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.0+1
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_ml_model_downloader: ^0.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_isolate: ^2.0.4
  google_generative_ai: ^0.4.3
  http: ^1.2.1
  image: ^4.2.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  tflite_flutter: ^0.11.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
