// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOOR9IYgxySib5Dw-rfBBtclwmdeznRZs',
    appId: '1:554502685675:web:5f0dbdbb9453d9f7e88fae',
    messagingSenderId: '554502685675',
    projectId: 'food-recognizer-d9e99',
    authDomain: 'food-recognizer-d9e99.firebaseapp.com',
    storageBucket: 'food-recognizer-d9e99.firebasestorage.app',
    measurementId: 'G-Z5S3GS87HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFe09_-KMWOlUz70mAHCudz2u14Oq1x24',
    appId: '1:554502685675:android:853ec6a24566a716e88fae',
    messagingSenderId: '554502685675',
    projectId: 'food-recognizer-d9e99',
    storageBucket: 'food-recognizer-d9e99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk5QE2JC8qIVizOzhiKzJ73C9sgArOV9Q',
    appId: '1:554502685675:ios:19402df35dd15c78e88fae',
    messagingSenderId: '554502685675',
    projectId: 'food-recognizer-d9e99',
    storageBucket: 'food-recognizer-d9e99.firebasestorage.app',
    iosBundleId: 'com.codesynesia.foodRecognizer',
  );
}
